name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu server
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Check out the code in your repository

  deploy:
    needs: build  # Ensure that the build job runs before deploy
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu server
    permissions:
      pages: write  # Allow the job to deploy to GitHub Pages
      id-token: write  # For token-based authentication

    environment:
      name: github-pages  # Name of the environment
      url: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/'  # URL for your GitHub Pages site

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5  # Set up GitHub Pages for deployment
      
      - name: Deploy
        uses: actions/deploy-pages@v4  # Deploy the contents to GitHub Pages
        with:
          branch: gh-pages  # Deploy to the 'gh-pages' branch (common convention for GitHub Pages)
          folder: .  # Deploy everything in the root folder (your HTML, CSS, etc.)
